apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-ms
spec:
  selector:
    matchLabels:
      app: registration-ms
  replicas: 2
  template:
    metadata:
      labels:
        app: registration-ms
    spec:
      # nodeSelector:
      #   label: value
      containers:
        - name: registration-app
          image: alexeybelous/registration:1.1
          livenessProbe:
            httpGet:
              path: /api/v1/probes/liveness
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/probes/readiness
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
        # - name: minikube-registration-storage
        #   image: alexeybelous/mongo:1.0
        #   resources:
        #     limits:
        #       memory: "128Mi"
        #       cpu: "500m"
        #   env:
        #     - name:
        #   ports:
        #     - containerPort: 27017
