version: "3"
services:
  storage:
    image: alexeybelous/mongo:1.0
    container_name: registration-storage
    ports:
      - "127.0.0.1:27017:27017" 
    environment: 
      - MONGODB_ADMIN_USER=root
      - AUTH=yes
      - MONGODB_ADMIN_PASS=root
      - MONGODB_APPLICATION_DATABASE=registration
      - MONGODB_APPLICATION_USER=minikube
      - MONGODB_APPLICATION_PASS=minikube