apiVersion: v1
kind: PersistentVolume
metadata:
  name: registration-storage-pv
  labels:
    type: local
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/belous.alexey/minikube-pv-root"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registration-storage-pvm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: registration-storage-pv
  resources:
    requests:
      storage: 300Mi
