apiVersion: v1
kind: Service
metadata:
  name: kube-lesson-service
spec:
  selector:
    app: kube-lesson
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-lesson
spec:
  selector:
    matchLabels:
      app: kube-lesson
  replicas: 4
  template:
    metadata:
      labels:
        app: kube-lesson
    spec:
      containers:
      - name: kube-lesson
        image: alexeybelous/kubelesson-api:latest
        ports:
        - containerPort: 8080